[package]
name = "yrs-warp"
version = "0.2.0"
edition = "2021"
description = "Yrs synchronization protocol using Warp web sockets"
license = "MIT"
authors = ["Bartosz Sypytkowski <b.sypytkowski@gmail.com>"]
keywords = ["crdt", "yrs", "warp"]
homepage = "https://github.com/y-crdt/yrs-warp/"
repository = "https://github.com/y-crdt/yrs-warp/"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib0 = "0.13"
yrs = "0.13"
y-sync = "0.1"
warp = "0.3"
futures-util = "0.3"
tokio = { version = "1.20", features = ["full"] }
async-trait = "0.1"